In [ ]:
import numpy as np



40


In [1]:
# 1. Create a 1D NumPy array containing numbers from 5 to 50 with a step of 5.
import numpy as np
arr = np.arange(5,51,5)
print(arr)

# 2. Create a 2D array of shape (4, 3) filled with ones.
arr = np.ones((4,3))
print(arr)

# 3. Create an array of 6 equally spaced values between 0 and 1.
arr = np.linspace(0,1,6)
print(arr)

# 4. Create a 3×3 identity matrix.
arr = np.eye(3)
print(arr)

# 5. Find the shape, size, number of dimensions, and data type of a given array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)

# 6. Convert the Python list [10, 20, 30, 40, 50] into a NumPy array.
li = [10, 20, 30, 40, 50]
print(np.array(li))

# 7. Reshape a 1D array of 16 elements into a 4×4 matrix.
arr = np.arange(1,17).reshape(4,4)
print(arr)

# 8. Flatten a 2D array into 1D using both flatten() and ravel(). Observe the difference.
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr.flatten())         # creates a copy of the original ones 
print(arr.ravel())           # creates a view of the original

# 9. Access the middle element of a 1D array.
arr = np.array([10, 20, 30, 40, 50])
mid = [len(arr)//2]                  #arr.size
print(mid)

# 10. Reverse a NumPy array without using loops.
arr = np.array([10, 20, 30, 40, 50])
reversed = arr[::-1]
print(reversed)



# 1. Extract all even-indexed elements from a NumPy array.
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(arr[::2])

# 2. Extract the last column from a 2D array.
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr[:,-1])

# 3. Slice a 1D array to get alternate elements starting from index 1.
arr = np.array([1, 22, 44, 3, 55])
print(arr[1::2])

# 4. Extract a 2×2 sub-matrix from a 3×3 matrix.
arr = np.random.rand(3,3)
print(arr)

sub = arr[0:2, 0:2]
print(sub)

# 5. Print all elements except the first and last element of an array.
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:-1])



# 1. Select all elements greater than 25 from a NumPy array.
arr = np.array([10, 25, 30, -5, 45, 50, -10, 60])
res = arr[arr > 25]
print(res)

# 2. Replace all negative values in an array with 0.
arr = np.array([10, 25, 30, -5, 45, 50, -10, 60])
arr[arr < 0] = 0
print(arr)

# 3. Extract only the elements divisible by 3.
arr = np.array([10, 21, 30, -5, 45, 50, -10, 60])
res = arr[arr % 3 == 0]
print(res)

# 4. Count how many elements are greater than the mean of the array.
arr = np.array([10, 21, 30, 5, 45, 50, -0, 60])
mean_val = arr.mean()
count = np.sum(arr > mean_val)
print("Mean: ", mean_val)
print("Count: ", count)


# 5. Find the indices of elements where the value is equal to 50.
arr = np.array([10, 21, 50, -5, 45, 50, -10, 60])
indices = np.where(arr == 50)
print(indices)


# 1. Add two NumPy arrays element-wise.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b
print(result)


# 2. Perform matrix multiplication of two compatible matrices.
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

result = np.dot(A, B)
print(result)

rslt = A @ B
print(rslt)

# 3. Add a scalar value 10 to every element of a NumPy array.
arr = np.array([10, 20, 30])

result = arr + 10
print(result)

# 4. Add a 1D array of shape (3,) to a 2D array of shape (2, 3) using broadcasting.
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
arr1d = np.array([10,20,30])

result = arr2d + arr1d
print(result)

[ 5 10 15 20 25 30 35 40 45 50]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0.  0.2 0.4 0.6 0.8 1. ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(2, 3)
6
2
[10 20 30 40 50]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[2]
[50 40 30 20 10]
[10 30 50 70]
[3 6]
[22  3]
[[0.33270057 0.07425619 0.67899727]
 [0.28614066 0.93599302 0.41326168]
 [0.27026151 0.43050722 0.05514767]]
[[0.33270057 0.07425619]
 [0.28614066 0.93599302]]
[20 30 40]
[30 45 50 60]
[10 25 30  0 45 50  0 60]
[21 30 45 60]
Mean:  27.625
Count:  4
(array([2, 5]),)
[5 7 9]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[20 30 40]
[[11 22 33]
 [14 25 36]]


In [ ]:
import numpy as np

# Create a 1-dimensional NumPy array
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)


# Create a 2-dimensional array with 2 rows and 3 columns
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2)


# Create a 3-dimensional array
arr3 = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(arr3)


# Create an array of 10 zeros
arr4 = np.zeros(10)
print(arr4)
print("ndim:", arr4.ndim)
print("shape:", arr4.shape)
print("size:", arr4.size)


# Create a 2D array of zeros with 3 rows and 4 columns
arr5 = np.zeros((3, 4))
print(arr5)
print("ndim:", arr5.ndim)
print("shape:", arr5.shape)
print("size:", arr5.size)


# Numbers from 1 to 12 and reshape into 3 rows and 4 columns
arr6 = np.arange(1, 13).reshape(3, 4)
print(arr6)
print("ndim:", arr6.ndim)
print("shape:", arr6.shape)
print("size:", arr6.size)


# 3 × 3 array containing numbers from 1 to 9
arr7 = np.arange(1, 10).reshape(3, 3)
print(arr7)
print("ndim:", arr7.ndim)
print("shape:", arr7.shape)
print("size:", arr7.size)


# np.arange() containing numbers from 10 to 30
arr8 = np.arange(10, 31)
print(arr8)
print("ndim:", arr8.ndim)
print("shape:", arr8.shape)
print("size:", arr8.size)


# Create 2D array
arr9 = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr9)
print("ndim:", arr9.ndim)
print("shape:", arr9.shape)
print("size:", arr9.size)


# 3D array with shape (2, 3, 4)
arr10 = np.arange(1, 25).reshape(2, 3, 4)
print(arr10)
print("ndim:", arr10.ndim)
print("shape:", arr10.shape)
print("size:", arr10.size)


# Q11. 20 elements → 4 rows and 5 columns
arr11 = np.arange(1, 21).reshape(4, 5)
print("\nQ11:")
print(arr11)
print("ndim:", arr11.ndim)
print("shape:", arr11.shape)
print("size:", arr11.size)


# Q12. Shape (2, 2, 3)
arr12 = np.arange(1, 13).reshape(2, 2, 3)
print(arr12)
print("ndim:", arr12.ndim)
print("shape:", arr12.shape)
print("size:", arr12.size)

In [2]:
import numpy as np
a = np.arange(10,31,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [3]:
a = np.linspace(1,33, 5)
a

array([ 1.,  9., 17., 25., 33.])

In [4]:
a = np.linspace(0,1,10)
a

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [5]:
a = np.linspace(10, 31, 5)
a

array([10.  , 15.25, 20.5 , 25.75, 31.  ])

In [ ]:
a = np.array([10, 20, 30])
print(a + 5) # [15 25 35]
print(a * 2) # [20 40 60]
print(a / 10) # [1. 2. 3.]
print(a ** 2) # squares


In [ ]:
a = np.array([[10, 20, 30], [20, 30, 40]])
print(a + 5) # [15 25 35]

print(a * 2)

[[15 25 35]
 [25 35 45]]


In [7]:
b = np.array([[1,2],[2,3]])
print(b *2)

[[2 4]
 [4 6]]


In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate([a,b]))

[1 2 3 4 5 6]


In [14]:
arr = np.array([1, 2, 3])
print(arr)
print(arr.dtype)
arr = arr.astype(float)
print(arr)

[1 2 3]
int64
[1. 2. 3.]


In [30]:
a = np.array([10, np.nan, 30, 40])
print(np.isnan(a))
print(np.nanmean(a))
print(np.nansum(a))


[False  True False False]
26.666666666666668
80.0
